// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface KeelPayloadEthereum$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "KeelPayloadEthereum";
  readonly sourceName: "src/libraries/KeelPayloadEthereum.sol";
  readonly abi: [{"inputs":[],"name":"execute","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"isExecutable","outputs":[{"internalType":"bool","name":"result","type":"bool"}],"stateMutability":"pure","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/libraries/KeelPayloadEthereum.sol";
  readonly buildInfoId: "solc-0_8_25-3a668e37e0001809778ce89d297f6f54dbb0a132";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["KeelPayloadEthereum"]: KeelPayloadEthereum$Type;
    ["src/libraries/KeelPayloadEthereum.sol:KeelPayloadEthereum"]: KeelPayloadEthereum$Type;
  }
}