// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ChainIdUtils$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ChainIdUtils";
  readonly sourceName: "src/libraries/ChainId.sol";
  readonly abi: [];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122097ea1a2979772cea9d22f005728dfe27067286b5b59470ff3e7df594cfdcc6e564736f6c63430008190033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122097ea1a2979772cea9d22f005728dfe27067286b5b59470ff3e7df594cfdcc6e564736f6c63430008190033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/libraries/ChainId.sol";
  readonly buildInfoId: "solc-0_8_25-3a668e37e0001809778ce89d297f6f54dbb0a132";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ChainIdUtils"]: ChainIdUtils$Type;
    ["src/libraries/ChainId.sol:ChainIdUtils"]: ChainIdUtils$Type;
  }
}