// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface LayerZeroPayloadCapture$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "LayerZeroPayloadCapture";
  readonly sourceName: "src/test-harness/LayerZeroPayloadCapture.sol";
  readonly abi: [];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212204f7fcd521b08bf38bfda7e1da06115b784d075f64bac62c9a44aed76b5f2b67b64736f6c63430008190033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212204f7fcd521b08bf38bfda7e1da06115b784d075f64bac62c9a44aed76b5f2b67b64736f6c63430008190033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/test-harness/LayerZeroPayloadCapture.sol";
  readonly buildInfoId: "solc-0_8_25-3a668e37e0001809778ce89d297f6f54dbb0a132";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["LayerZeroPayloadCapture"]: LayerZeroPayloadCapture$Type;
    ["src/test-harness/LayerZeroPayloadCapture.sol:LayerZeroPayloadCapture"]: LayerZeroPayloadCapture$Type;
  }
}