name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: true

    name: Hardhat project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Compile contracts
        run: |
          pnpm compile
        id: compile

      - name: Run Hardhat tests
        env:
          MAINNET_RPC_URL: ${{secrets.MAINNET_RPC_URL}}
        run: |
          pnpm test:solidity
        id: test

      - name: Install surfpool
        run: curl -sL https://run.surfpool.run/ | bash

      - name: Show Surfpool version
        run: ~/.local/bin/surfpool --version

      - name: Install submodule deps
        run: |
          cd tools/payload-validations
          pnpm install

      - name: Run spell e2e tests
        run: |
          ~/.local/bin/surfpool start &
          sleep 5
          pnpm test
